[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false
ffi = false
fs_permissions = []
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 64
depth = 64
fail_on_revert = true
